language: php

php:
  - 7.4

before_script:
  - composer install
  - composer dump-autoload

script:
  - vendor/bin/phpcs -p --standard=psr2 ./src
  - vendor/bin/phpcs -p --standard=psr2 ./tests
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="1c25834f4be890b0fc95be82e9eba2d920278cc12fe65c5abc42f202d905bf1d" --format=php-clover coverage.clover
